export const GET_MOVIES = 'GET_MOVIES';
export const LOADING_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const LOADING_MOVIES_FAILURE = 'LOADING_MOVIES_FAILURE ';
export const GET_MOVIES_TRENDING_SUCCESS = 'GET_MOVIES_TRENDING';
export const LOADING_MOVIES_TRENDING_START = 'LOADING_MOVIES_TRENDING_START';
export const LOADING_MOVIES_TRENDING_FAILURE =
  'LOADING_MOVIES_TRENDING_FAILURE';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';
export const LOADING_UPCOMING_MOVIES_START = 'LOADING_UPCOMING_MOVIES_START';
export const LOADING_UPCOMING_MOVIES_FAILURE =
  'LOADING_UPCOMING_MOVIES_FAILURE';
export const OPEN_ITEM = 'OPEN_ITEM';
export const CLOSE_ITEM = 'CLOSE_ITEM';
export const GET_LATEST_MOVIE = 'GET_LASTEST_MOVIE';
export const GET_ITEM_MODAL = 'GET_ITEM_MODAL';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES ';
